language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: V61ZvvKMnc3M2iQ5D/siId7b+IQnXCBCNCmYbV4U01xMNKmw/m0Akj6eIexufmaWqBQTv8ibtMbTI7A//MLZrtoA30FkHry/ETa2uyeh1SdfKZS2sOebEBT+2HQ1wpxGEq8x5lHZa8JGYUnXHACGRky1UWDUbwLo3ejzXR5h4WoAee9OKgu+KVtT5EZ+rU4RpNBXy8agIcX4iuRJCrSlhwebupM5NqNACGI3pqqYhRUH+f4sUpLvuEdS6wsnciMtto/NQD4k3zYQU1xiwTwiws6f2rfRjIpndmVh9SQEqiml8MAnXAUpyIihM2KoyLd4sIHkFuXFY+YK/9xO4PrAxz5KrqFes/nAnEZjm9ultlzc6gp9Bb9exUgD0Nt97vBHUGsCKsVWL3K9Iu9rPJgkyB26rkLioEAL/BN8SEnywZTxphI74WuykbtwPKTaJvn/+MXDmPAP/ayxsE8MxPUmz2JlfbykvOLYkeOPzfqR5RsIbeCujjFGx/gLEI8faCLWOBPiEappQTkKYesWYVl1L0KCvk2gOW4eAk3d7LAjMv9sXh32CJIsEsq4BeeOdS8n2x0IiWVVd3ZIHK0FXkfj9N5whRV6RrpRlEuIgM9TES59IeDuErqt/bsUNPSrt7aNfYLMSptuTsxw5p5Ik0QTMi/zLXVE2oiuFlh+ZCujzrE=
  app: floating-reef-78221
  on:
    repo: DarcyDeAngeloWoolsey/blog-app-mongoose-challenge-solution
